[package]
name = "dateparser"
version = "0.1.0"
authors = ["Rollie Ma <rollie@rollie.dev>"]
description = "Parse dates in string formats that are commonly used."
readme = "README.md"
homepage = "https://github.com/waltzofpearls/belt/tree/main/dateparser"
repository = "https://github.com/waltzofpearls/belt/tree/main/dateparser"
keywords = ["date", "time", "datetime", "parser", "parse"]
license = "MIT"
edition = "2018"

[dependencies]
anyhow = "1.0.40"
chrono = "0.4"
regex = "1.5.4"
