[package]
name = "belt"
version = "0.1.5"
authors = ["Rollie Ma <rollie@rollie.dev>"]
edition = "2018"
publish = false
description = "Know your time from a list of selected time zones"

[dependencies]
anyhow = "1.0.40"
chrono = "0.4"
chrono-tz = "0.5"
clap = "3.0.0-beta.2"
colored = "2.0.0"
confy = "0.4.0"
dateparser = { path = "../dateparser" }
directories = "^2.0"
prettytable-rs = "0.8.0"
serde = { version = "1.0.125", features = ["derive"] }

[dev-dependencies]
rand = "0.8.3"
regex = "1.5.4"
